const ACTION_BUTTONS_HEIGHT = '50px';
const BUTTON_HEIGHT = '30px';
const BUTTON_WIDTH = '100px';
const FOOTER_HEIGHT = '50px';
const ICON_SIZEH_HEIGHT = '15px';
const ICON_SIZE_WIDTH = ICON_SIZEH_HEIGHT;
const NAV_HEIGHT = '50px';

export {
  ACTION_BUTTONS_HEIGHT,
  BUTTON_HEIGHT,
  BUTTON_WIDTH,
  FOOTER_HEIGHT,
  ICON_SIZE_WIDTH,
  ICON_SIZEH_HEIGHT,
  NAV_HEIGHT,
};